---
- name: install os packages
  yum:
    name: "{{ packages }}"
    state: installed
  become: true

- name: create download directory
  file:
    path: "{{ download_dir }}/noobs"
    state: directory
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
    mode: 0755

- name: download noobs
  get_url:
    url: https://downloads.raspberrypi.org/NOOBS_lite_latest
    dest: '{{ download_dir }}/noobs_lite.zip'
  notify: extract noobs

- name: created raspbian directory
  file:
    path: '{{ download_dir }}/noobs/os/raspbian_{{ raspbian_flavor }}/'
    state: directory
    mode: 0755

- name: download os
  get_url:
    url: 'https://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}_latest'
    dest: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}.zip'
  notify: extract os

- name: download additional files
  get_url:
    url: "{{ item }}"
    dest: '{{ download_dir }}/noobs/os/raspbian_{{ raspbian_flavor }}/'
  with_items:
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/os.json
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/partition_setup.sh
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/partitions.json
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/root.tar.xz
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/boot.tar.xz

- name: configure recovery.cmd to autostart installation
  copy:
    src: recovery.cmdline
    dest: "/mnt/NOOBS"

- name: enable ssh on boot
  file:
    path: "{{ download_dir }}/SSH"
    state: file

# - name: copy wifi configuration
#   copy:
#     src: ./wpa_supplicant.conf
#     dest: /mnt/NOOBS/
#     mode: 0600
