---

- name: install unison
  apt:
    name:
      - unison
    state: present
  become: true

- name: create unison config directory
  file:
    path: "/home/{{ installation_os_user }}/.unison"
    owner: "{{ installation_os_user }}"
    group: "{{ installation_os_group }}"
    state: directory

- name: copy unison sync profile
  copy:
    src: "{{ item }}"
    dest: "/home/{{ installation_os_user }}/.unison/"
    owner: "{{ installation_os_user }}"
    group: "{{ installation_os_group }}"
  with_items:
    - sync_home.prf

- name: copy backup and restore script
  copy:
    src: "{{ item }}"
    dest: "/user/sbin/"
  with_items:
    - backup.sh
    - restore.sh
