---

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"


- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

# - name: upgrade pip
#   pip:
#     name:
#       - pip
#     extra_args: --upgrade

- name: install lzma modlue to support archive module with xz format
  pip:
    name:
      - pylzma
      - backports.lzma

- name: create download directory
  file:
    path: "{{ download_dir }}/noobs"
    state: directory
    owner: '{{ installation_os_user }}'
    group: '{{ installation_os_group }}'
    mode: 0755

- name: download noobs
  get_url:
    url: https://downloads.raspberrypi.org/NOOBS_lite_latest
    dest: '{{ download_dir }}/noobs_lite.zip'
  notify: extract noobs

- name: created raspbian directory
  file:
    path: '{{ download_dir }}/noobs/os/raspbian_{{ raspbian_flavor }}/'
    state: directory
    mode: 0755

- name: download os
  get_url:
    url: 'https://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}_latest'
    dest: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}.zip'
  notify: extract os

- name: download additional files
  get_url:
    url: "{{ item }}"
    dest: '{{ download_dir }}/noobs/os/raspbian_{{ raspbian_flavor }}/'
  with_items:
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/os.json
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/partition_setup.sh
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/partitions.json
    - http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/boot.tar.xz


- name: create root folder to extract raspbian root partition
  file:
    path: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}/root'
    state: directory
    mode: '0755'

- name: unarchive raspbian root partition
  unarchive:
    src: http://downloads.raspberrypi.org/raspbian_{{ raspbian_flavor }}/root.tar.xz
    dest: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}/root'
    remote_src: true

- name: copy firstboot service to raspbian root tarball
  copy:
    src: firstboot.service
    dest: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}/root/lib/systemd/system/firstboot.service'

- name: create symlink on root partition to enable firstboot service
  file:
    src: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}/root/lib/systemd/system/firstboot.service'
    dest: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}/root/etc/systemd/system/multi-user.target.wants/firstboot.service'
    state: link

- name: repack the raspbian root partition for installation
  archive:
    path: '{{ download_dir }}/raspbian_{{ raspbian_flavor }}/root'
    dest: '{{ download_dir }}/noobs/os/raspbian_{{ raspbian_flavor }}/root.tar.xz'
    format: xz

- name: configure recovery.cmd to autostart installation
  copy:
    src: recovery.cmdline
    dest: "/mnt/NOOBS"

- name: enable ssh on boot
  command: "touch {{ download_dir }}/noobs/SSH"
  args:
    creates: "{{ download_dir }}/noobs/SSH"

# - name: copy wifi configuration
#   copy:
#     src: ./wpa_supplicant.conf
#     dest: /mnt/NOOBS/
#     mode: 0600
