---

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

- name: install os packages
  yum:
    name:
      - unzip
      - gcc
      - net-tools
      - python-setuptools
      - python-pip
      - python-devel
      - xz-devel
    state: present
  become: true
